### PR TITLE
Initial work on adding linters

### PR DESCRIPTION
**Pull request by lsolesen**
If you think this looks alright, I will continue to add it to Radix also and fix the linting issues. Do not merge anything yet.

### CODE REVIEW

**Comment by lsolesen** [comment]
@arshad What's the verdict. Should I fix the linting going this road forward?

**Comment by shadcn** [comment]
@lsolesen Thanks for your work on this. A few questions / notes?
1. I've not looked into the lint space a lot but are there any other options other than a ruby-based linting library? Maybe something that works with node? We removed the ruby dependency in the latest Radix and opted for performance. I'd like to not go back to ruby if we can.
2. The double quotes is from Bootstrap. They use double quotes in their Scss.

**Comment by lsolesen** [comment]
Ad 1. I've found https://github.com/sasstools/sass-lint. I will try to add that in instead tonight. 
Ad 2. Do you prefer the double quotes - or single quotes for Radix?

**Comment by lsolesen** [comment]
I do not know whether this is official bootstrap, but another library is using this config: https://github.com/Wolox/rails-bootstrap/blob/master/.scss-lint.yml

**Comment by lsolesen** [comment]
We also have bootlint: https://github.com/twbs/bootlint#on-the-command-line

**Comment by shadcn** [comment]
1. Thanks for the link. I'll install it and test it.
2. I use single quotes mostly for personal projects but for Radix I'd like to keep it close to what Bootstrap is using. Let's do double quotes for Radix.

**Comment by shadcn** [comment]
Sorry didn't mean to close this. Reopening.

**Comment by lsolesen** [comment]
@arshad I will update the pull request. Should I start fixing linting also?

**Comment by shadcn** [comment]
@lsolesen Let's give the one based on node a try?

**Comment by lsolesen** [comment]
@arshad There you go --> https://travis-ci.org/lsolesen/radix/builds/122569622

**Comment by lsolesen** [comment]
@arshad Now I added the SCSS rules. If you review which rules to follow, then I can adjust the rules and fix the rest of the linting issues.

**Comment by lsolesen** [comment]
@arshad Do you have an online place where you hang out, so we could discuss live?

**Comment by shadcn** [comment]
@lsolesen Just tested the patch. This is looking really good. I'm seeing some warning in the Radix partials. I'll fix. Let's discuss the rules now. What's a good starting point?

Also, we need to remove the Gemfile and Gemfile.lock from the PR.

**Comment by lsolesen** [comment]
Yeah. Let me polish the PR. I think we should just use standard rules with
quotes as the exception. Its up to you.

Den ons. 13. apr. 2016 18.56 skrev Arshad Chummun <notifications@github.com

**Comment by lsolesen** [comment]
Closing this in favor of: https://github.com/radixtheme/radix/pull/15

**Pull request closed without merging**
